### ISSUE TITLE
Request the cold start of the training data file

### ISSUE THREAD

**Issue by Ngqgq** [kanz76/GMPNN-CS#3]
Thanks for contributing such a good article as GMPNN-CS, but the uploaded code seems to lack a way to generate a cold start file, data_preprocessing.py can only generate warm start training data files, if so, could you provide code to generate cold start training data?

**Comment by haoruilee** [comment]
Hello @Ngqgq ,

I came across your issue regarding the need for a way to generate a cold start file for this project. This is something I am also interested in. Have you made any progress on this issue since your last post, or have you found a solution? Any update you can share would be greatly appreciated.

Thank you!

**Comment by kanz76** [comment]
Please refer to [data_preprocessing_cold_start.py](https://github.com/kanz76/GMPNN-CS/blob/master/data_preprocessing_cold_start.py) for the generation of the data.
